#!/usr/bin/env python3
"""
Render the MCP App UIs in a normal browser, outside a host.

The apps only ever run inside an MCP host's sandboxed iframe, so there is no way to
look at them while developing. This fetches each app's HTML and a real tool result
from a running server over the actual /mcp endpoint, swaps the ext-apps SDK for a
local stub that replays that result, and serves the pages on a plain HTTP port.

Because the HTML comes from the server rather than from disk, this exercises the
real serving path - including AppHtmlLoader inlining the design tokens.

Each app is rendered twice, once per colour mode, so light and dark can be compared
side by side.

Usage:
    mvn spring-boot:run &                 # server must be up on :8080
    scripts/preview-apps.py               # build + serve on :8781
    scripts/preview-apps.py --no-serve    # just write the files
    scripts/preview-apps.py --app trip    # one app only

Then open http://localhost:8781/ and pick a page.
"""

import argparse
import http.server
import json
import functools
import os
import re
import sys
import urllib.error
import urllib.request

# name -> (resource uri, tool to call for sample data, tool arguments)
#
# The sample calls hit the live API, so what they exercise varies: the trip route is
# chosen to be multi-leg (rail, walk, air, bus) rather than for any particular
# condition. To look at a state that depends on live data - a disrupted trip, an
# occupancy reading - edit the arguments below to a route that currently has one.
APPS = {
    "trip": (
        "ui://trip/trip-map.html",
        "trip",
        {"from": "Oslo S", "to": "Trondheim S", "language": "en", "maxResults": 3},
    ),
    "departures": (
        "ui://departures/departures-board.html",
        "departures",
        {"stop": "Jernbanetorget", "language": "en", "numberOfDepartures": 8},
    ),
    "stops": (
        "ui://nearby/nearby-stops-map.html",
        "nearby-stops",
        {"location": "Jernbanetorget, Oslo", "language": "en"},
    ),
    "mobility": (
        "ui://mobility/nearby-mobility-map.html",
        "nearby-mobility",
        {"location": "Jernbanetorget, Oslo", "radius": 600, "language": "en"},
    ),
}

THEMES = ("light", "dark")

# Stands in for @modelcontextprotocol/ext-apps. Only the surface the apps actually
# touch: a tool result delivered once on connect, and the host theme.
MOCK_SDK = """\
// Generated by scripts/preview-apps.py - stand-in for @modelcontextprotocol/ext-apps.
// Replays a real CallToolResult captured from the server and reports a fixed theme.
export class App {
  constructor() { this.ontoolresult = null; this.onhostcontextchanged = null; }
  getHostContext() { return { theme: window.__MCP_PREVIEW_THEME__ }; }
  getHostCapabilities() { return {}; }
  getHostVersion() { return { name: "preview-harness", version: "1.0.0" }; }
  async connect() {
    setTimeout(() => this.ontoolresult && this.ontoolresult(window.__MCP_PREVIEW_RESULT__), 0);
  }
  async callServerTool() { return window.__MCP_PREVIEW_RESULT__; }
  async close() {}
}
"""

INDEX = """\
<!doctype html><meta charset="utf-8"><title>MCP app previews</title>
<style>
  body {{ font: 15px/1.5 system-ui, sans-serif; margin: 3rem auto; max-width: 34rem; }}
  h1 {{ font-size: 1.2rem; }}
  td {{ padding: .2rem .8rem .2rem 0; }}
  code {{ color: #666; }}
</style>
<h1>MCP app previews</h1>
<p><code>{server}</code></p>
<table>{rows}</table>
"""


def rpc(server, method, params):
    """One JSON-RPC call against the server's /mcp endpoint."""
    body = json.dumps({"jsonrpc": "2.0", "id": 1, "method": method, "params": params})
    req = urllib.request.Request(
        f"{server}/mcp",
        data=body.encode(),
        headers={
            "Content-Type": "application/json",
            "Accept": "application/json, text/event-stream",
        },
    )
    with urllib.request.urlopen(req, timeout=60) as resp:
        payload = json.load(resp)
    if "error" in payload:
        raise SystemExit(f"{method} failed: {payload['error']}")
    return payload["result"]


def build(server, out_dir, names):
    os.makedirs(out_dir, exist_ok=True)
    with open(os.path.join(out_dir, "mock-app.js"), "w") as fh:
        fh.write(MOCK_SDK)

    written = []
    for name in names:
        uri, tool, args = APPS[name]
        print(f"{name}: reading {uri}")
        html = rpc(server, "resources/read", {"uri": uri})["contents"][0]["text"]

        print(f"{name}: calling {tool}")
        result = rpc(server, "tools/call", {"name": tool, "arguments": args})
        if result.get("isError"):
            text = result.get("content", [{}])[0].get("text", "")
            raise SystemExit(f"  tool {tool} returned an error: {text[:300]}")

        # Point the SDK import at the local stub. Everything else - including the
        # inlined design tokens - is served exactly as the host would receive it.
        html, n = re.subn(
            r'https://unpkg\.com/@modelcontextprotocol/ext-apps@[^"\']+',
            "./mock-app.js",
            html,
        )
        if not n:
            raise SystemExit(f"  {name}: no ext-apps import found - did the CDN URL change?")

        for theme in THEMES:
            inject = (
                "<script>"
                f"window.__MCP_PREVIEW_RESULT__={json.dumps(result)};"
                f"window.__MCP_PREVIEW_THEME__={json.dumps(theme)};"
                "</script>"
            )
            page = html.replace("</head>", inject + "\n</head>", 1)
            filename = f"{name}-{theme}.html"
            with open(os.path.join(out_dir, filename), "w") as fh:
                fh.write(page)
            written.append(filename)

    rows = "".join(
        "<tr><td><a href='{0}-light.html'>{0}</a></td>"
        "<td><a href='{0}-light.html'>light</a></td>"
        "<td><a href='{0}-dark.html'>dark</a></td></tr>".format(n)
        for n in names
    )
    with open(os.path.join(out_dir, "index.html"), "w") as fh:
        fh.write(INDEX.format(server=server, rows=rows))

    print(f"\nwrote {len(written)} pages to {out_dir}")
    return written


def serve(out_dir, port):
    handler = functools.partial(http.server.SimpleHTTPRequestHandler, directory=out_dir)
    # file:// cannot load ES modules, so the pages have to come off an HTTP origin.
    with http.server.ThreadingHTTPServer(("127.0.0.1", port), handler) as httpd:
        print(f"serving http://localhost:{port}/  (ctrl-c to stop)")
        try:
            httpd.serve_forever()
        except KeyboardInterrupt:
            print()


def main():
    default_out = os.path.join(
        os.path.dirname(os.path.abspath(__file__)), os.pardir, "target", "app-preview"
    )
    ap = argparse.ArgumentParser(description=__doc__,
                                 formatter_class=argparse.RawDescriptionHelpFormatter)
    ap.add_argument("--server", default="http://localhost:8080",
                    help="running MCP server (default: %(default)s)")
    ap.add_argument("--out", default=os.path.normpath(default_out),
                    help="output directory (default: target/app-preview)")
    ap.add_argument("--port", type=int, default=8781, help="preview port (default: %(default)s)")
    ap.add_argument("--app", action="append", choices=sorted(APPS),
                    help="only this app (repeatable; default: all)")
    ap.add_argument("--no-serve", action="store_true", help="write files and exit")
    opts = ap.parse_args()

    try:
        build(opts.server, opts.out, opts.app or list(APPS))
    except urllib.error.URLError as e:
        sys.exit(f"cannot reach {opts.server} ({e.reason}). Is `mvn spring-boot:run` up?")

    if not opts.no_serve:
        serve(opts.out, opts.port)


if __name__ == "__main__":
    main()
